apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeframe-registry
  labels:
    name: kubeframe-registry
spec:
  replicas: 1
  selector:
    matchLabels:  
      name: kubeframe-registry 
  template:
    metadata:
      labels:
        name: kubeframe-registry
    spec:
      containers:
        - name: kubeframe-registry
          image: quay.io/jparrill/registry:2 
          ports:
            - name: registry 
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: "/var/lib/registry"
            - name: certs
              mountPath: "/certs"
              readOnly: true
            - name: auth
              mountPath: "/auth"
              readOnly: true
          env:
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: "/certs/tls.crt"
            - name: REGISTRY_HTTP_TLS_KEY
              value: "/certs/tls.key"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: certs
          secret:
            secretName: certs-secret
        - name: auth
          secret:
            secretName: auth-secret
