---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: kubeframe-registry
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce
